# Generated by Django 6.1.1 on 2026-09-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.BigIntegerField(blank=True, null=True, verbose_name='Код клієнта')),
                ('client_name', models.CharField(max_length=100, verbose_name='Назва клієнта')),
                ('client_registration_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регіон реєстрації')),
                ('client_registration_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто реєстрації')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронна пошта')),
                ('client_phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефону')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
