# Generated by Django 6.1.1 on 2026-10-06 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Введіть 10 цифр, наприклад 0960663212')], verbose_name='Номер телефону'),
        ),
    ]
