# Generated by Django 6.1.1 on 2026-09-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_adress_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('client_adress_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто')),
                ('client_adress_street', models.CharField(max_length=100, null=True, verbose_name='Вулиця')),
                ('client_adress_building_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер будівлі')),
                ('client_adress_phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефону дільниці')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='Client.client', verbose_name='Клієнт')),
            ],
        ),
    ]
